// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidoCompra.Contextos;

namespace PedidoCompra.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20190301042957_CriandoTabelaCartao")]
    partial class CriandoTabelaCartao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PedidoCompra.Domain.Pedidos.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Codigo");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("Vencimento");

                    b.HasKey("Id");

                    b.ToTable("Cartao");
                });

            modelBuilder.Entity("PedidoCompra.Domain.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CartaoId");

                    b.Property<DateTime>("Criado");

                    b.Property<string>("Descricao");

                    b.Property<byte>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PedidoCompra.Domain.Pedidos.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<Guid>("PedidoId");

                    b.Property<decimal>("Quantidade");

                    b.Property<decimal>("ValorUnitario");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItem");
                });

            modelBuilder.Entity("PedidoCompra.Domain.Pedidos.Pedido", b =>
                {
                    b.HasOne("PedidoCompra.Domain.Pedidos.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PedidoCompra.Domain.Pedidos.PedidoItem", b =>
                {
                    b.HasOne("PedidoCompra.Domain.Pedidos.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
